# Common Labels
labels:
  app: "hge-read"

# Ingress Configs
ingress:
  enabled: true
  additionalAnnotations: |
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  path: "hge-read(/|$)(.*)"  

# Container Configs
image:
  repository: "hasura/graphql-engine"
  tag: "v1.3.3-patch.1"
replicas: "1"
enableConsole: "true"
healthChecks:
  enabled: true
  livenessProbePath: "/healthz"
  readinessProbePath: "/healthz"
resources: |
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 500m  
    memory: 1Gi

# Additional Container Envs
env: |
  - name: HASURA_GRAPHQL_DATABASE_URL
    valueFrom:
      secretKeyRef:
        key: HASURA_GRAPHQL_DATABASE_URL_READ
        name: secrets                 
  - name: HASURA_GRAPHQL_ENABLE_CONSOLE
    value: {{ .Values.enableConsole | quote }}
  - name: HASURA_GRAPHQL_CORS_DOMAIN
    value: "*"
  - name: HASURA_GRAPHQL_ADMIN_SECRET
    valueFrom:
      secretKeyRef:
        key: HASURA_GRAPHQL_ADMIN_SECRET_READ
        name: secrets
  - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
    value: startup,http-log,query-log    
  - name: HASURA_GRAPHQL_ENABLE_ALLOWLIST
    value: "true"   
  - name: HASURA_GRAPHQL_CONSOLE_ASSETS_DIR
    value: "/srv/console-assets" 
  - name: HASURA_GRAPHQL_PG_CONNECTIONS
    value: "50"   