version: 2
endpoint: http://localhost:8088
admin_secret: "STtP4MjPkFw5NaejTmmvfhxvmNBYm5c68zNb66eArjA6FbfcnAn5GqcMkrbHQ6j5"
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
