{{- with .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .namespace }}
data: 
{{- range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}