# Common Labels
labels:
  app: "hge"

# Container Configs
image:
  repository: "hasura/graphql-engine"
  tag: "v1.3.3-patch.1"
replicas: "1"
enableConsole: "true"
healthChecks:
  enabled: true
  livenessProbePath: "/healthz"
  readinessProbePath: "/healthz"
resources: |
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 750m  
    memory: 1Gi

# Additional Container Envs
env: |
  - name: HASURA_GRAPHQL_DATABASE_URL
    valueFrom:
      secretKeyRef:
        key: HASURA_GRAPHQL_DATABASE_URL
        name: secrets                 
  - name: HASURA_GRAPHQL_ENABLE_CONSOLE
    value: {{ .Values.enableConsole | quote }}
  - name: HASURA_GRAPHQL_CORS_DOMAIN
    value: "*"
  - name: HASURA_GRAPHQL_ADMIN_SECRET
    valueFrom:
      secretKeyRef:
        key: HASURA_GRAPHQL_ADMIN_SECRET
        name: secrets
  - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
    value: startup,http-log,webhook-log,websocket-log,query-log    
  - name: HASURA_GRAPHQL_ENABLE_ALLOWLIST
    value: "true"   
  - name: HASURA_GRAPHQL_CONSOLE_ASSETS_DIR
    value: "/srv/console-assets" 
  - name: HASURA_GRAPHQL_PG_CONNECTIONS
    value: "50"
  - name: HASURA_GRAPHQL_CONNECTIONS_PER_READ_REPLICA
    value: "20"
  - name: HASURA_GRAPHQL_LIVE_QUERIES_MULTIPLEXED_BATCH_SIZE
    value: "30"     