{{- define "common.serviceaccount" -}}
{{- $serviceName := include "common.name" . -}}
{{- if .Values.serviceAccount -}}
---
apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets: {{ toYaml .Values.global.imagePullSecrets | nindent 2 }}
{{- end }}
metadata:
  name: {{ .Values.serviceAccount | default $serviceName }}
  namespace: {{ template "common.namespace" . }}
  labels:
{{- include "common.labels" . | nindent 4 }}                            
{{- end }} 
{{- end -}}
