name: npm build, lint, test and publish
on:
  push:
    branches: [ main ]
    paths:
    - XState-Chatbot/**
  pull_request:
    branches: [ main ]
    paths:
    - XState-Chatbot/**  
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/npm@master
        with:
          args: install
      - name: npm test
        uses: actions/npm@master
        with:
          args: run test
      - name: npm lint
        uses: actions/npm@master
        with:
          args: run lint
      - name: docker build
        uses: actions/docker/cli@master
        with:
          args: build -t Swasth-Digital-Health-Foundation/C19CareAssist .
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}          
      - name: docker push
        uses: actions/docker/cli@master
        with:
          push: true
          tags: docker.pkg.github.com/${{ github.repository }}/XState-chatbot:${{ github.ref }}-${{ github.sha }}
