name: XState-Chatbot-CI 

on:
  workflow_dispatch:
    inputs:
      git_branch_or_tag:
        description: 'git_branch_or_tag'
        required: true
      docker_tag:
        description: 'docker_tag'
        required: true
        default: 'false'

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.git_branch_or_tag }}
  
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Preparing Required Vars
        run : |
          echo "short_SHA=$(/usr/bin/git log -1 --format='%H' | cut -c 1-7)" >> $GITHUB_ENV    
      
      - name: Build and push( Branch and SHA )
        if: ${{ github.event.inputs.docker_tag == 'false' }}
        uses: docker/build-push-action@v2
        with:
          context: XState-Chatbot/nodejs
          push: true
          tags: swasthapp/chatbot:${{ github.event.inputs.git_branch_or_tag }}-${{ env.short_SHA }} 

      - name: Build and push( Docker Tag )
        if: ${{ github.event.inputs.docker_tag != 'false' }}
        uses: docker/build-push-action@v2
        with:
          context: XState-Chatbot/nodejs
          push: true
          tags: swasthapp/chatbot:${{ github.event.inputs.docker_tag }}